apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-nodejs
    app.kubernetes.io/part-of: test-application
  name: devfile-nodejs
  namespace: appstudio
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: devfile-nodejs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: devfile-nodejs
    spec:
      containers:
      - image: quay.io/karthik_jk/devfile-nodejs@sha256:2c7920263f5842bdbe500b3efdc63f6292dfda459de14814edd50200b1dbff4c
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
